### ISSUE TITLE
Cannot build program because it requires Siv3D.hpp

### ISSUE THREAD

**Issue by RyutoSetsujin** [Ryoga-exe/Sigmabeat2#21]
I don't fully know how this works, but for some reason it needs Siv3D.hpp and I don't really know where that is supposed to go...

**Comment by Ryoga-exe** [comment]
It requires Siv3D v0.6.4  to build. Please download Siv3D v0.6.4 from [here](https://siv3d.github.io/) and build program again.
It also requires [Microsoft Visual C++ 2022 17.2 (Install "Desktop development with C++" from the Visual Studio Installer)](https://visualstudio.microsoft.com/downloads/) for the IDE.

I should have mentioned this in the README but forgot, sorry...
